### PR TITLE
[NonNasa] Registration request delay introduction

### PR DESCRIPTION
**Pull request by tristone-cz**

### CODE REVIEW

**Comment by omerfaruk-aran** [comment]
Hello,

The solution you implemented can temporarily fix the issue, but it might create challenges in terms of user experience. Users would need to figure out the correct delay interval through trial and error, which might not be the most user-friendly approach.

Instead, I suggest implementing a dynamic delay adjustment algorithm. This algorithm would automatically increase the delay until a successful response is received from the devices, and then retain the optimal value. This way, users won't need to manually input a parameter, and the process becomes fully automated.

Could you implement such a revision? If you prefer, I can also work on this issue and share a PR. Since I don't have a Non-NASA device, I can't test the problems and solutions you’re experiencing, but I can provide this solution and wait for your testing results.

Thank you for your contributions as well.

**Comment by tristone-cz** [comment]
Hi.

Well, I understand your idea but I have doubts if it is worth to and if it is easily feasible.
Few arguments:
- it seems to be rare issue as I am first one noticing it, maybe related to old units only, no idea
- it is happening only in case of full power outage for the whole AC (power loss, maintenance, winter pause, ...)
    -  as such I am not sure how to retain the value, one ESP is turned off, all knowledge is lost
    - also for debugging it is problematic as only wireless logging is available in this situation and as such missing first 10-12 seconds of output
- it seems that the active registration is not happening and is not needed at all once I introduce the delay - after approx. 30-32 seconds since power up I can see the communication between ESP and AC to start even if the delay did not yet passed.

I think I would be able to write such an algo but in fact right now I have no idea what shall be the logic as I do not know the root cause of the problem at the AC unit. 
Base on experience on my AC it looks like 40+ seconds is safe interval. And as this problems happens only during startup from full power off state which is in most cases rare event I am not sure that trying to be oversophisticated will not bring more troubles than benefits.

I understand you user-friendly approach, I am usually on the same wave, but this time, not sure if it brings so much additional benefit compared to this simple workaround approach. All the people using this integration must be skilled enough anyway so one more tricky parameter shall not surprise them.

**Review by omerfaruk-aran — CHANGES_REQUESTED** [review]
Hello,

Firstly, thank you for your feedback. I appreciate your insights, and I find your reasoning quite logical. You are correct that these kinds of issues might be rare and could be limited to older units. The fact that it only occurs in full power outage situations and that communication starts even without an active delay is an interesting observation.

However, the current solution requiring users to define a parameter could lead to some complexity for them. Therefore, I suggest that you first resolve any conflicts and then test the dynamic delay management approach we proposed.

Suggestion:
First, add the following code to the `components/samsung_ac/protocol_non_nasa.cpp` file:

- Create a `bool` variable and a counter to track the delay duration at the start:

```cpp
bool controller_register_allow = false;
const uint32_t start_millis = millis();
```

- Modify the code block managing the dynamic delay:

```cpp
// If we're not currently registered, keep sending a registration request until it has
// been confirmed by the outdoor unit.
if (!controller_registered)
{
    // Increase delay dynamically until the outdoor unit responds successfully
    long delay_interval = (non_nasa_registration_delay_interval * 1000);
    if (now - start_millis >= delay_interval) {
        controller_register_allow = true;
    }
    if (controller_register_allow) {
        send_register_controller(target);
    }
}
```

After implementing this update, you can test the new dynamic delay control and observe how stable the communication is in different situations (such as after power outages or maintenance). Since I don’t have a Non-NASA device on hand to test this directly, I would appreciate it if you could implement and test this solution on your side and share the results.

Once again, thank you for your contributions and valuable feedback!

**Comment by tristone-cz** [comment]
Hi.

After a lot of thinking how to establish automatic dynamic delay I made a step aside.
Based on my tests it seems sufficient just to stop flooding the outdoor unit with the registration requests several times a second. And instead of that be more gentle 😉 

* Define an interval for registration requests
```
	bool controller_register_allow = false;
	uint32_t start_millis = millis();
	uint32_t registration_interval = 2000;
```

* And send only one registration request in the interval
```
// If we're not currently registered, keep sending a registration request until it has
// been confirmed by the outdoor unit.
if (!controller_registered)
            {
                // Prevent registration flood and send the registration request in a reasonable interval
		if (now - start_millis >= registration_interval) {
		    controller_register_allow = true;
		}
		if (controller_register_allow) {
		    send_register_controller(target);
		    controller_register_allow = false;
		    start_millis = millis();
		}
            }
```

What do you think?
No need for complex elaboration of dynamic delay times, no need to find out a way how to remember the value, etc. etc.
And can be used for all units, no significant impact. Maybe just a 1-2 seconds slower component init after power-on recovery ...

**Comment by omerfaruk-aran** [comment]
Hi,

Firstly, thank you for sharing your suggestion. Your solution seems logical and provides a simpler approach to avoid overloading the outdoor unit with unnecessary requests. I think it’s a great idea.

However, since I don't have a NonNASA device to test it on, I need to ensure the solution works properly before merging. Could you please add the proposed changes to your PR, resolve the existing conflicts, and commit the updates?

Once you’ve done that, I’ll share the code with the community for broader testing. Based on the test results from different devices, we can then decide on releasing it.

Thank you again for your contribution and efforts. It’s much appreciated!

**Comment by tristone-cz** [comment]
I will create new PR.
This one contains also the new configuration parameter etc. Many changes compared to what is needed for the new approach. Better to start from scratch.

**Pull request closed without merging**
